// config/timeseriesConfig.js
export const TIMESERIES_CONFIG = {
    PREFETCH_PAGES: 3,
    PAGE_SIZE: 15000000,
    PREFETCH_DELAY: 100,
    THROTTLE_RENDER_DELAY: 250,
    THROTTLE_DATA_DELAY: 50,
    MAX_REQUESTED_PAGES: 20,
    SPIKE_HEIGHT_RATIO: 2,
    XOFFSET: 0
}